// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHxbeBS0wtRJyZYS-0V7u1SG1C43n4nfg',
    appId: '1:397750141912:web:befcd51c392f240f2e28ad',
    messagingSenderId: '397750141912',
    projectId: 'guias-de-remision-4c4a6',
    authDomain: 'guias-de-remision-4c4a6.firebaseapp.com',
    storageBucket: 'guias-de-remision-4c4a6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvgpVsFbVF5gUvIisKxD_0ao20QS8R4DI',
    appId: '1:397750141912:android:c73692baa378a4932e28ad',
    messagingSenderId: '397750141912',
    projectId: 'guias-de-remision-4c4a6',
    storageBucket: 'guias-de-remision-4c4a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJBXZWTzE2ZoZU6s_SBVaOpbVhZAHQ8FM',
    appId: '1:397750141912:ios:de0c0ba05146973c2e28ad',
    messagingSenderId: '397750141912',
    projectId: 'guias-de-remision-4c4a6',
    storageBucket: 'guias-de-remision-4c4a6.appspot.com',
    iosBundleId: 'com.example.appRemision',
  );

}